stages:
  - deploy

repoupdate:
  stage: deploy
  variables:
    TWINE_USERNAME: Salamek
  before_script:
    - apt-get update -y
    - apt-get install twine python3-setuptools python3-pip -y
  script:
    - python3 setup.py sdist
    - twine upload dist/*
  tags:
    - debian
  only:
    - tags
